// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGck3b5njuOnXgsnlEJ5c4hk2GgL8WJzQ',
    appId: '1:205621401825:android:d77121905770db93793fa0',
    messagingSenderId: '205621401825',
    projectId: 'axent-579ca',
    storageBucket: 'axent-579ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD7gTBJsN3uWgs3lP2WcPn73Cc6nPMeYY',
    appId: '1:205621401825:ios:1848ffaa0c506df3793fa0',
    messagingSenderId: '205621401825',
    projectId: 'axent-579ca',
    storageBucket: 'axent-579ca.firebasestorage.app',
    androidClientId: '205621401825-r2rq51d13q3emplta66mamepjao69a2f.apps.googleusercontent.com',
    iosClientId: '205621401825-cb7ucraip7vtd8opv7j1s74cvajv8vbf.apps.googleusercontent.com',
    iosBundleId: 'com.juddebert.axent',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnOJf79hONDd_WEZsybufpzW1Z9sGzoXU',
    appId: '1:205621401825:web:2302157cbee6c47b793fa0',
    messagingSenderId: '205621401825',
    projectId: 'axent-579ca',
    authDomain: 'axent-579ca.firebaseapp.com',
    storageBucket: 'axent-579ca.firebasestorage.app',
    measurementId: 'G-D054844DCB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD7gTBJsN3uWgs3lP2WcPn73Cc6nPMeYY',
    appId: '1:205621401825:ios:7ff69bf5f699a701793fa0',
    messagingSenderId: '205621401825',
    projectId: 'axent-579ca',
    storageBucket: 'axent-579ca.firebasestorage.app',
    androidClientId: '205621401825-r2rq51d13q3emplta66mamepjao69a2f.apps.googleusercontent.com',
    iosClientId: '205621401825-6uvekjga3qq3hm2r6jvfng5rb8mtj7oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionfrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnOJf79hONDd_WEZsybufpzW1Z9sGzoXU',
    appId: '1:205621401825:web:a9e11ceebf5a11b8793fa0',
    messagingSenderId: '205621401825',
    projectId: 'axent-579ca',
    authDomain: 'axent-579ca.firebaseapp.com',
    storageBucket: 'axent-579ca.firebasestorage.app',
    measurementId: 'G-CM2Y3K9QBX',
  );

}